Update Build Actions

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -1,80 +1,100 @@
-name: SonarCloud analysis
+name: Vercel Production Deployment
+env:
+  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
+  NODE_VERSION: '20'
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
+  PRODUCTION_DEPLOYMENT_URL: 'https://pokejut.vercel.app/'
 
 on:
   push:
-    branches: ["main"]
-  pull_request:
-    branches: ["main"]
-    types: [opened, synchronize, reopened]
-  workflow_dispatch:
-
-permissions:
-  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
+    branches:
+      - main
 
 jobs:
-  Build:
+  Deploy-Production:
     runs-on: ubuntu-latest
-
+    outputs:
+      deployment-url: ${{ steps.deploy.outputs.deployment-url }}
     steps:
-      - uses: actions/checkout@v4.1.3
-        with:
-          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
+      - uses: actions/checkout@latest
 
-      - name: Cache Dependencies
-        uses: actions/cache@v1
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: ${{ runner.os }}-node-
+      - name: Install Vercel CLI
+        run: npm install --global vercel@latest
 
-      - name: Setup Node 18
-        uses: actions/setup-node@v2
+      - name: Set up Node.js
+        uses: actions/setup-node@latest
         with:
-          node-version: "18"
+          node-version: ${{ env.NODE_VERSION }}
 
       - name: Install dependencies
-        run: npm i
+        run: npm install
 
-  Lint:
-    needs: Build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Lint
-        run: npm run lint
-
-  Test:
-    needs: Build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Test and coverage
+      - name: Run tests with coverage
         run: npm run cover
 
-      - name: Archive production artifacts
-        uses: actions/upload-artifact@v4.3.2
-        with:
-          name: coverage
-          path: coverage
-
-  Analysis:
-    needs: [Lint, Test]
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v4.1.3
-        with:
-          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
-
-      - name: Download artifacts
-        uses: actions/download-artifact@v4.1.5
-        with:
-          name: coverage
-          path: coverage
-
-      - name: Analyze with SonarCloud
+      # Run SonarQube analysis
+      - name: Run SonarQube Scanner
         uses: SonarSource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
         with:
-          args: -Dsonar.projectKey=Stradivary_pokejut
+          args: >
+            -Dsonar.projectKey=Stradivary_pokejut
             -Dsonar.organization=stradivary
+            -Dsonar.host.url=https://sonarcloud.io
+            -Dsonar.login=${{ env.SONAR_TOKEN }}
+            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+            -Dsonar.coverage.exclusions=src/**/*.test.ts, src/**/*.test.tsx, __snapshots__/**/*, src/**/*.spec.ts, src/**/*.spec.tsx, src/domain/use-cases/simulator/presistor.ts, src/data/entities/**/*, src/main.tsx, src/routes.tsx
+
+      # Check SonarQube Quality Gate Status
+      - name: Check SonarQube Quality Gate Status
+        id: quality_gate
+        run: |
+          URL="https://sonarcloud.io/api/qualitygates/project_status?projectKey=projectkey_web-pokemon-evolution"
+          TOKEN="${{ secrets.SONAR_TOKEN }}"
+          STATUS="NONE"
+          while [ "$STATUS" != "OK" ] && [ "$STATUS" != "ERROR" ]; do
+            RESPONSE=$(curl -u $TOKEN: "$URL")
+            STATUS=$(echo $RESPONSE | jq -r '.projectStatus.status')
+            if [ "$STATUS" == "NONE" ]; then
+              echo "Quality Gate status is pending..."
+              sleep 10
+            elif [ "$STATUS" == "ERROR" ]; then
+              echo "Quality Gate failed."
+              echo "::set-output name=quality_gate_passed::false"
+              exit 0
+            fi
+          done
+          echo "Quality Gate passed."
+          echo "::set-output name=quality_gate_passed::true"
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      # Conditional step based on Quality Gate result
+      - name: Halt Deployment Due to Failed Quality Gate
+        if: steps.quality_gate.outputs.quality_gate_passed != 'true'
+        run: |
+          echo "Halting deployment due to failed Quality Gate."
+          exit 1
+
+      # Build and deploy to Vercel and capture deployment URL
+      - name: Pull Vercel Environment Information
+        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
+
+      - name: Build Project Artifacts
+        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
+      
+      - name: Deploy Project Artifacts to Vercel
+        if: success() && steps.quality_gate.outputs.quality_gate_passed == 'true'
+        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
+
+      - name: Extract Deployment URL
+        if: success()
+        id: extract-url
+        run: echo "::set-output name=deployment-url::$(tail -1 deployment-url.txt)"
+        
+      - name: ZAP Scan
+        uses: zaproxy/action-baseline@latest
+        with:
+          target: ${{ env.PRODUCTION_DEPLOYMENT_URL }}
